#!/bin/bash

BVENV=$1

if [ -z "$BVENV" ]; then 
	echo "Please suggest an environment (dev/prod)"
fi

if [ "$BVENV" == "dev" ]; then
	echo Calling lagoon dev deployment
	/usr/local/bin/lagoon -i /storage/blue-value/id_ed25519 -p blue-value -e dev --force deploy latest
elif [ "$BVENV" == "prod" ]; then
	echo Calling prod dev deployment
	/usr/local/bin/lagoon -i /storage/blue-value/id_ed25519 -p blue-value -e prod --force deploy latest
else
	echo "I don't know what to do wit $BVENV"
fi

